-- MySQL Script generated by MySQL Workbench
-- Sun Jan 12 22:20:58 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema n00bs
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema n00bs
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `n00bs` DEFAULT CHARACTER SET latin1 ;
USE `n00bs` ;

-- -----------------------------------------------------
-- Table `n00bs`.`games`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `n00bs`.`games` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `rating` FLOAT NULL DEFAULT NULL,
  `summary` VARCHAR(10000) NULL DEFAULT NULL,
  `release_date` VARCHAR(255) NULL DEFAULT NULL,
  `cover_url` VARCHAR(256) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 119358
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `n00bs`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `n00bs`.`users` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `uid` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `n00bs`.`comment_rating`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `n00bs`.`comment_rating` (
  `id_user` BIGINT(20) NOT NULL,
  `id_game` BIGINT(20) NOT NULL,
  `comment` VARCHAR(256) NULL DEFAULT NULL,
  `rating` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`id_user`, `id_game`),
  INDEX `fk_comment_game` (`id_game` ASC) VISIBLE,
  CONSTRAINT `fk_comment_game`
    FOREIGN KEY (`id_game`)
    REFERENCES `n00bs`.`games` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comment_user`
    FOREIGN KEY (`id_user`)
    REFERENCES `n00bs`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `n00bs`.`companies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `n00bs`.`companies` (
  `id` BIGINT(25) NOT NULL,
  `company` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `n00bs`.`games_companies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `n00bs`.`games_companies` (
  `id_game` BIGINT(25) NOT NULL,
  `id_company` BIGINT(25) NOT NULL,
  PRIMARY KEY (`id_game`, `id_company`),
  INDEX `FK_games_companies` (`id_company` ASC) VISIBLE,
  CONSTRAINT `FK_games_companies`
    FOREIGN KEY (`id_company`)
    REFERENCES `n00bs`.`companies` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_games_companies_game`
    FOREIGN KEY (`id_game`)
    REFERENCES `n00bs`.`games` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `n00bs`.`genres`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `n00bs`.`genres` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 33
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `n00bs`.`games_genres`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `n00bs`.`games_genres` (
  `game_id` BIGINT(20) NOT NULL,
  `genre_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`game_id`, `genre_id`),
  INDEX `fk_games_genres_genre` (`genre_id` ASC) VISIBLE,
  CONSTRAINT `fk_games_genres_game`
    FOREIGN KEY (`game_id`)
    REFERENCES `n00bs`.`games` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_games_genres_genre`
    FOREIGN KEY (`genre_id`)
    REFERENCES `n00bs`.`genres` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `n00bs`.`platforms`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `n00bs`.`platforms` (
  `id` BIGINT(20) NOT NULL,
  `name` VARCHAR(225) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `n00bs`.`games_platforms`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `n00bs`.`games_platforms` (
  `game_id` BIGINT(20) NOT NULL,
  `platform_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`game_id`, `platform_id`),
  INDEX `FK_games_platforms_platform_id` (`platform_id` ASC) VISIBLE,
  CONSTRAINT `FK_games_platforms_game_id`
    FOREIGN KEY (`game_id`)
    REFERENCES `n00bs`.`games` (`id`),
  CONSTRAINT `FK_games_platforms_platform_id`
    FOREIGN KEY (`platform_id`)
    REFERENCES `n00bs`.`platforms` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `n00bs`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `n00bs`.`orders` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `number` VARCHAR(255) NOT NULL,
  `user_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_orders_users_user_id` (`user_id` ASC) VISIBLE,
  CONSTRAINT `FK_orders_users_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `n00bs`.`users` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `n00bs`.`orders_games`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `n00bs`.`orders_games` (
  `order_id` BIGINT(20) NOT NULL,
  `game_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`order_id`, `game_id`),
  INDEX `FK_orders_games_game_id` (`game_id` ASC) VISIBLE,
  CONSTRAINT `FK_orders_games_game_id`
    FOREIGN KEY (`game_id`)
    REFERENCES `n00bs`.`games` (`id`),
  CONSTRAINT `FK_orders_games_order_id`
    FOREIGN KEY (`order_id`)
    REFERENCES `n00bs`.`orders` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `n00bs`.`users_games`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `n00bs`.`users_games` (
  `user_id` BIGINT(20) NOT NULL,
  `game_id` BIGINT(20) NOT NULL,
  `rating` FLOAT NOT NULL,
  `review` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`user_id`, `game_id`),
  INDEX `FK_users_games_game_id` (`game_id` ASC) VISIBLE,
  CONSTRAINT `FK_users_games_game_id`
    FOREIGN KEY (`game_id`)
    REFERENCES `n00bs`.`games` (`id`),
  CONSTRAINT `FK_users_games_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `n00bs`.`users` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `n00bs`.`wishlist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `n00bs`.`wishlist` (
  `id_user` BIGINT(20) NOT NULL,
  `id_game` BIGINT(20) NOT NULL,
  PRIMARY KEY (`id_user`, `id_game`),
  INDEX `fk_wishlist_game` (`id_game` ASC) VISIBLE,
  CONSTRAINT `fk_wishlist_game`
    FOREIGN KEY (`id_game`)
    REFERENCES `n00bs`.`games` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_wishlist_user`
    FOREIGN KEY (`id_user`)
    REFERENCES `n00bs`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
